/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardTodoImport } from './routes/dashboard/todo'
import { Route as DashboardGroupImport } from './routes/dashboard/group'
import { Route as DashboardCategoryImport } from './routes/dashboard/category'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTodoRoute = DashboardTodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardGroupRoute = DashboardGroupImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCategoryRoute = DashboardCategoryImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/category': {
      id: '/dashboard/category'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardCategoryImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/group': {
      id: '/dashboard/group'
      path: '/group'
      fullPath: '/dashboard/group'
      preLoaderRoute: typeof DashboardGroupImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/todo': {
      id: '/dashboard/todo'
      path: '/todo'
      fullPath: '/dashboard/todo'
      preLoaderRoute: typeof DashboardTodoImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardCategoryRoute: typeof DashboardCategoryRoute
  DashboardGroupRoute: typeof DashboardGroupRoute
  DashboardTodoRoute: typeof DashboardTodoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoryRoute: DashboardCategoryRoute,
  DashboardGroupRoute: DashboardGroupRoute,
  DashboardTodoRoute: DashboardTodoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/category': typeof DashboardCategoryRoute
  '/dashboard/group': typeof DashboardGroupRoute
  '/dashboard/todo': typeof DashboardTodoRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/category': typeof DashboardCategoryRoute
  '/dashboard/group': typeof DashboardGroupRoute
  '/dashboard/todo': typeof DashboardTodoRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/category': typeof DashboardCategoryRoute
  '/dashboard/group': typeof DashboardGroupRoute
  '/dashboard/todo': typeof DashboardTodoRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/category'
    | '/dashboard/group'
    | '/dashboard/todo'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/category'
    | '/dashboard/group'
    | '/dashboard/todo'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/category'
    | '/dashboard/group'
    | '/dashboard/todo'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/category",
        "/dashboard/group",
        "/dashboard/todo",
        "/dashboard/"
      ]
    },
    "/dashboard/category": {
      "filePath": "dashboard/category.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/group": {
      "filePath": "dashboard/group.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/todo": {
      "filePath": "dashboard/todo.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
